django_simple_account/urls.py
from django.urls import path, register_converter

from . import views, converters

register_converter(converters.OAuthSession, 'oauth')
register_converter(converters.ConfirmationEmailSession, 'confirmation-email')
register_converter(converters.ConfirmationForgotPasswordSession, 'confirmation-forgotpassword')

app_name = 'django-simple-account'

urlpatterns = [
    path('login/', views.Login.as_view(), name="login"),
    path('signup/', views.Signup.as_view(), name="signup"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('oauth/google/', views.OAuthGoogle.as_view(), name='oauth-google'),
    path('oauth/facebook/', views.OAuthFacebook.as_view(), name='oauth-facebook'),
    path('oauth/completion/<oauth:session>/', views.OAuthCompletion.as_view(), name='oauth-completion'),
    path(
        'confirmation/email/<confirmation-email:session>/',
        views.ConfirmationEmail.as_view(),
        name='confirmation-email'
    ),

    path('forgotpassword/', views.ForgotPassword.as_view(), name='forgotpassword'),
    path(
        'forgotpassword/<confirmation-forgotpassword:session>/',
        views.ForgotPasswordConfirmation.as_view(),
        name='forgotpassword-confirmation'
    ),
    path('facebook/deactivate/', views.FacebookDeactivate.as_view(), name='facebook-deactivate'),
]

# if 'rest_framework' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         # path('api-auth/', include('rest_framework.urls'))
#         path('api/v1/', api.APIUser.as_view(), name='accounts-api-user'),
#         path('api/v1/<int:id>/', api.APIUserDetail.as_view(), name='accounts-api-user-detail'),
#     ]

django_simple_account/models.py
import hashlib

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import validators


def unique_file_path_avatar(instance, filename):
    instance.original_file_name = filename
    m = hashlib.sha256()
    m.update("{id}".format(id=instance.user.id).encode('UTF-8'))
    return 'avatar/{hash}-{file}'.format(hash=m.hexdigest(), file=instance.original_file_name)


class Profile(models.Model):
    GENDER = (
        (1, _('Male')),
        (2, _('Female')),
    )

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name=_("User")
    )

    gender = models.SmallIntegerField(
        choices=GENDER,
        null=True,
        blank=True,
        verbose_name=_("Gender")
    )

    birth_date = models.DateField(
        null=True,
        blank=True,
        verbose_name=_("Birth date")
    )

    phone = models.BigIntegerField(
        null=True,
        blank=True,
        validators=[validators.mobile_number],
        verbose_name=_("Mobile phone"),
    )

    avatar = models.ImageField(upload_to=unique_file_path_avatar, null=True, blank=True)

    def __str__(self):
        """ Override output print object """
        return 'User profile {user}'.format(user=self.user)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")


class OAuth(models.Model):
    PROVIDER = (
        (1, 'Google'),
        (2, 'Facebook'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("User"))
    oauth_id = models.CharField(max_length=255, verbose_name=_("OAuth ID"))
    provider = models.IntegerField(choices=PROVIDER, verbose_name=_("Server"))

    class Meta:
        """ Meta class object OAuth in ORM Django """
        unique_together = (('oauth_id', 'provider'),)
        verbose_name = _("OAuth")
        verbose_name_plural = _("OAuth")

django_simple_account/views.py
import base64
import hashlib
import hmac
import json
import logging
import os
from importlib import import_module

import requests
from django.conf import settings
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from . import forms, converters, models, signals

logger = logging.getLogger(__name__)


class Login(generic.FormView):
    form_class = forms.Login
    template_name = "django_simple_account/login.html"
    success_url = '/'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        if self.request.GET.get('next'):
            logger.debug("next redirect {next}".format(next=self.request.GET.get('next')))
            return self.request.GET.get('next')
        else:
            logger.debug("next redirect {next}".format(next=self.success_url))
            return self.success_url

    def form_valid(self, form):
        response = super().form_valid(form)
        auth.login(self.request, form.get_user())
        return response

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = 400
        return response


class Logout(generic.RedirectView):
    permanent = False
    query_string = True
    url = '/'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            auth.logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class Signup(generic.FormView):
    form_class = forms.Signup
    template_name = "django_simple_account/signup.html"
    success_url = settings.LOGIN_URL

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = 400
        return response

    def form_valid(self, form):
        response = super().form_valid(form)
        form.confirmation(request=self.request)
        return response


class ConfirmationEmail(generic.View):
    form_class = forms.Signup

    def get(self, request, session: converters.ConfirmationEmailSession, *args, **kwargs):
        data = {}
        for item in ['username', 'last_name', 'first_name', 'email', 'password1', 'password2', 'params']:
            data[item] = getattr(session, item)
        form = self.form_class(data=data)

        if not form.is_valid():
            messages.error(self.request, _("The link in the email confirmation email is out of date"))
            return redirect(settings.LOGIN_URL)

        if session.action != 'signup':
            messages.error(self.request, _("The link in the email confirmation email is out of date"))
            return redirect(settings.LOGIN_URL)

        user = form.save()
        auth.login(self.request, user)

        # Send signal
        signals.signup_user.send(
            sender=self.__class__,
            user=user,
            is_oauth=False,
            params=data.get('params'),
        )

        session.session.delete()

        messages.success(self.request, _("Your address has been successfully verified"))
        return redirect(session.next)


class OAuthFacebook(generic.FormView):
    form_class = forms.OAuthFacebook
    success_url = '/'
    template_name = 'django_simple_account/oauth_facebook.html'

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = 400
        return response

    def form_valid(self, form):
        access_token = form.cleaned_data.get('access_token')
        params = {
            'fields': 'id,last_name,first_name,picture.width(512).height(512){url,height,width},email',
            'access_token': access_token,
        }
        response = requests.get('https://graph.facebook.com/v6.0/me', params=params)
        if response.status_code == 200:
            j = response.json()

            session_store = import_module(settings.SESSION_ENGINE).SessionStore
            session = session_store()
            session.set_expiry(60 * 60 * 3)

            session['oauth_id'] = j.get('id')
            session['last_name'] = j.get('last_name', "")
            session['first_name'] = j.get('first_name', "")
            session['provider'] = 2
            session['email'] = None
            session['username'] = None
            session['avatar'] = None

            if j.get('picture') and j.get('picture').get('data') and j.get('picture').get('data').get('url'):
                session['avatar'] = j.get('picture').get('data').get('url')

            email = j.get('email')
            if j.get('email'):
                email = email.strip().lower()
                user = email.rsplit('@', 1)[0]
                user = str(user).replace(".", "_")

                session['email'] = email
                session['username'] = user

            session.create()
            return JsonResponse({'session': session.session_key})


class OAuthGoogle(generic.FormView):
    form_class = forms.OAuthGoogle
    success_url = '/'
    template_name = 'django_simple_account/oauth_google.html'

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = 400
        return response

    def form_valid(self, form):
        """

        """
        oauth_response = requests.post("https://oauth2.googleapis.com/token", data={
            'client_id': getattr(settings, 'OAUTH_GOOGLE_CLIENT_ID', os.environ.get('OAUTH_GOOGLE_CLIENT_ID')),
            'client_secret': getattr(settings, 'OAUTH_GOOGLE_SECRET_KEY', os.environ.get('OAUTH_GOOGLE_SECRET_KEY')),
            'code': form.cleaned_data.get('code'),
            'grant_type': 'authorization_code',
            'redirect_uri': "{scheme}://{host}".format(
                scheme=self.request.META.get('HTTP_X_FORWARDED_PROTO') or self.request.scheme,
                host=self.request.get_host(),
                path=self.request.path,
            ),

        })

        j = oauth_response.json()
        if j.get('error'):
           return JsonResponse({'error': j.get('error_description')}, status=400)

        oauth_response = requests.get(
            url="https://www.googleapis.com/oauth2/v1/userinfo",
            headers={'Authorization': 'Bearer {access_token}'.format(access_token=j.get('access_token'))}
        )
        j = oauth_response.json()
        if j.get('error'):
            return JsonResponse({'error': j.get('error').get('message')}, status=400)

        session_store = import_module(settings.SESSION_ENGINE).SessionStore
        session = session_store()
        session.set_expiry(60 * 60 * 3)

        session['oauth_id'] = j.get('id')
        session['email'] = None
        session['username'] = None
        session['first_name'] = j.get('given_name', "")
        session['last_name'] = j.get('family_name', "")
        session['avatar'] = j.get('picture')
        session['provider'] = 1

        if j.get('email_verified'):
            email = j.get('email')
            if email:
                email = email.strip().lower()
                user = email.rsplit('@', 1)[0]
                session['email'] = email

                user = str(user).replace(".", "_")
                session['username'] = user

        session.create()
        return JsonResponse({'session': session.session_key})


class OAuthCompletion(generic.FormView):
    form_class = forms.OAuthCompletion
    success_url = '/'
    template_name = 'django_simple_account/oauth_completion.html'

    def form_invalid(self, form):
        response = super().form_invalid(form)
        response.status_code = 400
        return response

    def get_success_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        else:
            return self.success_url

    def get(self, request, *args, **kwargs):
        session = kwargs.get('session')
        oauth = models.OAuth.objects.filter(oauth_id=session.oauth_id, provider=session.provider)[:1]
        if oauth.exists():
            user = oauth.get().user

            # Download avatar
            if session.avatar:
                response = requests.get(url=session.avatar)
                if response.status_code == 200:
                    user.profile.avatar.save('{user_id}.jpg'.format(user_id=user.id), ContentFile(response.content))

            auth.login(self.request, user)
            session.session.delete()
            return redirect(self.get_success_url())

        if session.email:
            user = User.objects.filter(email=session.email)[:1]
            if user.exists():
                user = user.get()

                # Download avatar
                if session.avatar:
                    response = requests.get(url=session.avatar)
                    if response.status_code == 200:
                        user.profile.avatar.save('{user_id}.jpg'.format(user_id=user.id), ContentFile(response.content))

                auth.login(self.request, user)
                models.OAuth.objects.create(oauth_id=session.oauth_id, provider=session.provider, user=user)

                # Send signal
                signals.signup_user.send(
                    sender=self.__class__,
                    user=user,
                    is_oauth=True,
                    params=request.GET.dict()
                )

                session.session.delete()
                return redirect(self.get_success_url())

        return super().get(request)

    def form_valid(self, form):
        session = self.kwargs.get('session')
        user = form.save(session=session)

        # Download avatar
        if session.avatar:

django_simple_account/templates/django_simple_account/blank.html
{% extends "django_simple_account/common.html" %}

django_simple_account/templates/django_simple_account/forgot_password.html
{% extends "django_simple_account/common.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Password recovery" %}{% endblock %}

{% block content %}
    <div class="brand-wrapper">
        <img src="{% static "django_simple_account/assets/images/logo.svg" %}" alt="logo" class="logo">
    </div>
    <p class="login-card-description">{% trans "Password recovery" %}</p>

    {% if form.non_field_errors %}
        <div class="alert alert-danger div-max-width" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <small id="{{ field.auto_id }}" class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        {% endfor %}
        <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit"  value="{% trans "Submit" %}">
    </form>

    <p class="login-card-footer-text">
        {% trans "I have an account?" %}
        {% if request.GET.urlencode %}
            <a href="{% url 'django-simple-account:login' %}?{{ request.GET.urlencode }}" class="text-underline text-reset">{% trans "Login here" %}</a>
        {% else %}
            <a href="{% url 'django-simple-account:login' %}" class="text-underline text-reset">{% trans "Login here" %}</a>
        {% endif %}
    </p>
    </div>
{% endblock %}

django_simple_account/templates/django_simple_account/forgot_password_confirmation.html
{% extends "django_simple_account/common.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content %}
    <div class="brand-wrapper">
        <img src="{% static "django_simple_account/assets/images/logo.svg" %}" alt="logo" class="logo">
    </div>
    <p class="login-card-description">{% trans "Change password" %}</p>

    {% if form.non_field_errors %}
        <div class="alert alert-danger div-max-width" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <small id="{{ field.auto_id }}" class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        {% endfor %}
        <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit"  value="{% trans "Submit" %}">
    </form>

    <p class="login-card-footer-text">
        {% trans "I have an account?" %} <a href="{% url 'django-simple-account:login' %}" class="text-underline text-reset">{% trans "Login here" %}</a>
    </p>
{% endblock %}

django_simple_account/templates/django_simple_account/forgotpassword.html
{% extends "django_simple_account/common.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Password recovery" %}{% endblock %}

{% block content %}
    <div class="brand-wrapper">
        <img src="{% static "django_simple_account/assets/images/logo.svg" %}" alt="logo" class="logo">
    </div>
    <p class="login-card-description">{% trans "Password recovery" %}</p>

    {% if form.non_field_errors %}
        <div class="alert alert-danger div-max-width" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <small id="{{ field.auto_id }}" class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        {% endfor %}
        <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit"  value="{% trans "Submit" %}">
    </form>

    <p class="login-card-footer-text">
        {% trans "I have an account?" %} <a href="{% url 'django-simple-account:login' %}" class="text-underline text-reset">{% trans "Login here" %}</a>
    </p>
    </div>
{% endblock %}

django_simple_account/templates/django_simple_account/login.html
{% extends "django_simple_account/common.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Sign into your account" %}{% endblock %}

{% block js %}
    <script src="https://apis.google.com/js/client:platform.js?onload=start" async defer></script>
    <script>
        {% if OAUTH_GOOGLE_CLIENT_ID %}
            function start() {
                gapi.load('auth2', function() {
                    let auth2 = gapi.auth2.init({
                        client_id: "{{ OAUTH_GOOGLE_CLIENT_ID }}",
                    });

                    function signInCallback(authResult) {
                        if (authResult['code']){
                            $.ajax({
                                type: 'POST',
                                url: '{% url "django-simple-account:oauth-google" %}',
                                data: {
                                    code: authResult['code']
                                },
                                //timeout: 1,
                                beforeSend: function(xhr, settings) {
                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                },
                                success: function(result) {
                                    let session = result['session'];
                                    {% if request.GET.urlencode %}
                                        window.location.href = "../oauth/completion/" + session + "/?{{ request.GET.urlencode }}";
                                    {% else %}
                                        window.location.href = "../oauth/completion/" + session + "/?next=/";
                                    {% endif %}
                                },
                                error: function (jqXHR, textStatus, errorThrown){
                                    if(textStatus == "error") {
                                        if (jqXHR.status == 400){
                                            console.error(jqXHR.responseJSON['error']);
                                        }
                                    }
                                }
                            });
                        }
                    }

                    $('[data-oauth="google"]').click(function() {
                        auth2.grantOfflineAccess().then(signInCallback);
                    });
                });
            }
        {% endif %}

        {% if OAUTH_FACEBOOK_CLIENT_ID %}
            // Facebook OAuth
            $.getScript('https://connect.facebook.net/en_US/sdk.js', function(){
                FB.init({
                    appId: '{{ OAUTH_FACEBOOK_CLIENT_ID }}',
                    version: 'v2.7'
                });

                $('[data-oauth="facebook"]').on('click', function() {
                    FB.login( function(response) {
                        if (response.status == "connected"){
                            $.ajax({
                                type: 'POST',
                                url: '{% url "django-simple-account:oauth-facebook" %}',
                                data: {
                                    access_token: response['authResponse']['accessToken']
                                },
                                beforeSend: function(xhr, settings) {
                                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                                },
                                success: function(result) {
                                    let session = result['session'];
                                    {% if request.GET.urlencode %}
                                        window.location.href = "../oauth/completion/" + session + "/?{{ request.GET.urlencode }}";
                                    {% else %}
                                        window.location.href = "../oauth/completion/" + session + "/?next=/";
                                    {% endif %}
                                }
                            });
                        }
                    }, {scope: 'public_profile,email'});
                });
            });
        {% endif %}
    </script>

{% endblock %}

{% block content %}
    <div class="brand-wrapper">
        <img src="{% static "django_simple_account/assets/images/logo.svg" %}" alt="logo" class="logo">
    </div>
    <p class="login-card-description">{% trans "Sign into your account" %}</p>
    {% if form.non_field_errors %}
        <div class="alert alert-danger div-max-width" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit"  value="{% trans "Login" %}">
    </form>

    <div style="padding-bottom: 20px;">
        {% if request.GET.urlencode %}
            <a href="{% url 'django-simple-account:forgotpassword' %}?{{ request.GET.urlencode }}" class="forgot-password-link">{% trans "Forgot password?" %}</a>
        {% else %}
            <a href="{% url 'django-simple-account:forgotpassword' %}" class="forgot-password-link">{% trans "Forgot password?" %}</a>
        {% endif %}
    </div>
    <p class="login-card-footer-text">
        {% trans "Don't have an account?" %}

        {% if request.GET.urlencode %}
            <a href="{% url 'django-simple-account:signup' %}?{{ request.GET.urlencode }}" class="text-underline text-reset">{% trans "Register here" %}</a>
        {% else %}
            <a href="{% url 'django-simple-account:signup' %}" class="text-underline text-reset">{% trans "Register here" %}</a>
        {% endif %}
    </p>
    <hr>

    <div class="row">
        {% if OAUTH_GOOGLE_CLIENT_ID %}
            <div class="col-md-4" style="padding: 10px;">
                <button type="button" data-oauth="google" style="height: 40px; border-width: 0; background: white; color: #737373; border-radius: 5px; white-space: nowrap; box-shadow: 1px 1px 0px 1px rgba(0,0,0,0.05); transition-property: background-color, box-shadow; transition-duration: 150ms; transition-timing-function: ease-in-out; padding: 0;">
                    <span style="display: inline-block; vertical-align: middle; margin: 0px 0 8px 8px; width: 18px; height: 18px; box-sizing: border-box;">
                        <svg viewBox="0 0 366 372" xmlns="http://www.w3.org/2000/svg">
                            <path d="M125.9 10.2c40.2-13.9 85.3-13.6 125.3 1.1 22.2 8.2 42.5 21 59.9 37.1-5.8 6.3-12.1 12.2-18.1 18.3l-34.2 34.2c-11.3-10.8-25.1-19-40.1-23.6-17.6-5.3-36.6-6.1-54.6-2.2-21 4.5-40.5 15.5-55.6 30.9-12.2 12.3-21.4 27.5-27 43.9-20.3-15.8-40.6-31.5-61-47.3 21.5-43 60.1-76.9 105.4-92.4z" id="Shape" fill="#EA4335"/>
                            <path d="M20.6 102.4c20.3 15.8 40.6 31.5 61 47.3-8 23.3-8 49.2 0 72.4-20.3 15.8-40.6 31.6-60.9 47.3C1.9 232.7-3.8 189.6 4.4 149.2c3.3-16.2 8.7-32 16.2-46.8z" id="Shape" fill="#FBBC05"/>
                            <path d="M361.7 151.1c5.8 32.7 4.5 66.8-4.7 98.8-8.5 29.3-24.6 56.5-47.1 77.2l-59.1-45.9c19.5-13.1 33.3-34.3 37.2-57.5H186.6c.1-24.2.1-48.4.1-72.6h175z" id="Shape" fill="#4285F4"/>
                            <path d="M81.4 222.2c7.8 22.9 22.8 43.2 42.6 57.1 12.4 8.7 26.6 14.9 41.4 17.9 14.6 3 29.7 2.6 44.4.1 14.6-2.6 28.7-7.9 41-16.2l59.1 45.9c-21.3 19.7-48 33.1-76.2 39.6-31.2 7.1-64.2 7.3-95.2-1-24.6-6.5-47.7-18.2-67.6-34.1-20.9-16.6-38.3-38-50.4-62 20.3-15.7 40.6-31.5 60.9-47.3z" fill="#34A853"/>
                        </svg>
                    </span>
                    <span style="display: inline-block; vertical-align: middle; padding: 0 12px; font-size: 13px; font-weight: bold; font-family: 'Roboto',arial,sans-serif;">{% trans "Sign in with Google" %}</span>
                </button>
            </div>
        {% endif %}

        {% if OAUTH_FACEBOOK_CLIENT_ID %}
            <div class="col-md-4" style="padding: 10px;">
                <button type="button" data-oauth="facebook" style="height: 40px; border-width: 0; background: white; color: #737373; border-radius: 5px; white-space: nowrap; box-shadow: 1px 1px 0px 1px rgba(0,0,0,0.05); transition-property: background-color, box-shadow; transition-duration: 150ms; transition-timing-function: ease-in-out; padding: 0;">
                    <span style="display: inline-block; vertical-align: middle; margin: 0px 0 8px 8px; width: 18px; height: 18px; box-sizing: border-box;">
                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="73 0 267 266.9" enable-background="new 73 0 267 266.9" xml:space="preserve">
                            <path id="Blue_1_" fill="#157DC3" d="M321.1,262.3c7.9,0,14.2-6.4,14.2-14.2V18.8c0-7.9-6.4-14.2-14.2-14.2H91.8C84,4.6,77.6,11,77.6,18.8v229.3c0,7.9,6.4,14.2,14.2,14.2H321.1z"/>
                            <path id="f" fill="#FFFFFF" d="M255.4,262.3v-99.8h33.5l5-38.9h-38.5V98.8c0-11.3,3.1-18.9,19.3-18.9l20.6,0V45c-3.6-0.5-15.8-1.5-30-1.5c-29.7,0-50,18.1-50,51.4v28.7h-33.6v38.9h33.6v99.8H255.4z"/>
                        </svg>
                    </span>
                    <span data-oauth="facebook-text" style="display: inline-block; vertical-align: middle; padding: 0 12px; font-size: 13px; font-weight: bold; font-family: 'Roboto',arial,sans-serif;">{% trans "Sign in with Facebook" %}</span>
                </button>
            </div>
        {% endif %}

    </div>
{% endblock %}

django_simple_account/templates/django_simple_account/signup.html
{% extends "django_simple_account/common.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Sign into your account" %}{% endblock %}

{% block content %}
    <div class="brand-wrapper">
        <img src="{% static "django_simple_account/assets/images/logo.svg" %}" alt="logo" class="logo">
    </div>
    <p class="login-card-description">{% trans "Sign Up" %}</p>

    {% if form.non_field_errors %}
        <div class="alert alert-danger div-max-width" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.auto_id }}">{{ field.label|capfirst }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <small id="{{ field.auto_id }}" class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        {% endfor %}
        <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit"  value="{% trans "Sign Up" %}">
    </form>

    <div style="padding-bottom: 20px;">
        {% if request.GET.urlencode %}
            <a href="{% url 'django-simple-account:forgotpassword' %}?{{ request.GET.urlencode }}" class="forgot-password-link">{% trans "Forgot password?" %}</a>
        {% else %}
            <a href="{% url 'django-simple-account:forgotpassword' %}" class="forgot-password-link">{% trans "Forgot password?" %}</a>
        {% endif %}
    </div>
    <p class="login-card-footer-text">
        {% trans "I have an account?" %}
        {% if request.GET.urlencode %}
            <a href="{% url 'django-simple-account:login' %}?{{ request.GET.urlencode }}" class="text-underline text-reset">{% trans "Login here" %}</a>
        {% else %}
            <a href="{% url 'django-simple-account:login' %}" class="text-underline text-reset">{% trans "Login here" %}</a>
        {% endif %}
    </p>
    </div>
{% endblock %}